### PR TITLE
Power-domain PnR Fix

### PR DESCRIPTION
**Pull request by Kuree**
This PR implements the PnR fix for power domain. The idea is that each core will have a `nop` instruction. 
- For PE, this can be add where `data0 = 0` and `data1 = 0`, similar thing for 1bit LUT.
- For MEM, this can be reading from SRAM at 0 etc.

For now there is no valid tests since I'm not sure how to do that in verilator yet.

### CODE REVIEW

**Comment by rsetaluri** [comment]
Can you briefly explain how the "fixer" class will be used?

**Comment by Kuree** [comment]
The `PowerDomainFixer` is responsible for deciding which tile to turn on or off, and how to add additional routing and PE/MEM configuration to prevent `x` propagation.

As a result, it needs the PnR result as well as `nop` instruction for PE/MEM to produce the power domain fix.

**Comment by rsetaluri** [comment]
Thanks for the info.

**Comment by Kuree** [comment]
Will be added in different places.

**Pull request closed without merging**
