### PR TITLE
Global Signal wiring function change according to global buffer-interconnect interface change

### PR DESCRIPTION
**Pull request by kongty**
This PR changes global signal wiring.
As global buffer now has port group same number as the number of cgra columns.

It wires global buffer and interconnect accordingly.

Note: Do not delete this branch after merge yet. Garnet `master` is pinned to use this branch. Once this one is merged, I will change `garnet` to use `master` branch of `canal`. After that, I will remove this branch.

### CODE REVIEW

**Comment by rsetaluri** [comment]
@kong0329 I'm not sure we want to constrain these passes in this way. It seems more advisable to keep the parameter external and have the logic of computing that as a function of the specific global buffer in garnet itself. That way if we change the global buffer in another way, we don't have to adjust this code.

**Comment by kongty** [comment]
@rsetaluri Sure. I just added here directly because it was the way we used to do, but putting it into `global_buffer` folder seems more reasonable to me as well. @Kuree How do you think?

**Comment by Kuree** [comment]
I agree with Raj that this should be in garnet.

**Comment by kongty** [comment]
got it. I will close this PR then. Do not remove branch until I move this function to `garnet` please.

**Pull request closed without merging**
